### ISSUE TITLE
Which file is the micropython load?

### ISSUE THREAD

**Issue by mpechner** [pvanallen/esp32-getstarted#1]
Download Micropython software binary for ESP32
Which of these files?
Standard firmware:
esp32-ppp-fix.bin (latest)
esp32-bluetooth.bin
esp32-20190522-v1.10-372-gc03f81c63.bin
esp32-20190125-v1.10.bin
esp32-20180511-v1.9.4.bin

Firmware with SPIRAM support:
esp32spiram-20190522-v1.10-372-gc03f81c63.bin (latest)
esp32spiram-20190125-v1.10.bin

**Comment by pvanallen** [comment]
Yeah, it's confusing with so many different versions. The current release right now is v1.10

https://github.com/micropython/micropython/releases

So I would pick the core version of that unless you have specific needs: esp32-20190125-v1.10.bin
